// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------- //
// Abhadra_Interpreter //
// ------------------- //

#define Abhadra_Interpreter_wrap_target 30
#define Abhadra_Interpreter_wrap 31

static const uint16_t Abhadra_Interpreter_program_instructions[] = {
    0x003e, //  0: jmp    !x, 30                     
    0x0015, //  1: jmp    21                         
    0x0037, //  2: jmp    !x, 23                     
    0x001e, //  3: jmp    30                         
    0x005e, //  4: jmp    x--, 30                    
    0x001e, //  5: jmp    30                         
    0xa029, //  6: mov    x, !x                      
    0x001e, //  7: jmp    30                         
    0x009e, //  8: jmp    y--, 30                    
    0x001e, //  9: jmp    30                         
    0xa04a, // 10: mov    y, !y                      
    0x001e, // 11: jmp    30                         
    0xa0e2, // 12: mov    osr, y                     
    0x6001, // 13: out    pins, 1                    
    0x00ed, // 14: jmp    !osre, 13                  
    0x001e, // 15: jmp    30                         
    0xe03f, // 16: set    x, 31                      
    0x4001, // 17: in     pins, 1                    
    0x0051, // 18: jmp    x--, 17                    
    0xa026, // 19: mov    x, isr                     
    0x001e, // 20: jmp    30                         
    0x40fa, // 21: in     osr, 26                    
    0x001e, // 22: jmp    30                         
    0x80a0, // 23: pull   block                      
    0x6025, // 24: out    x, 5                       
    0x003e, // 25: jmp    !x, 30                     
    0x0017, // 26: jmp    23                         
    0xa0e1, // 27: mov    osr, x                     
    0x6001, // 28: out    pins, 1                    
    0x00fc, // 29: jmp    !osre, 28                  
            //     .wrap_target
    0x80a0, // 30: pull   block                      
    0x60a5, // 31: out    pc, 5                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program Abhadra_Interpreter_program = {
    .instructions = Abhadra_Interpreter_program_instructions,
    .length = 32,
    .origin = -1,
};

static inline pio_sm_config Abhadra_Interpreter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + Abhadra_Interpreter_wrap_target, offset + Abhadra_Interpreter_wrap);
    return c;
}

static inline void hello_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = hello_program_get_default_config(offset);
    // Map the state machine's OUT pin group to one pin, namely the `pin`
    // parameter to this function.
    sm_config_set_out_pins(&c, pin, 1);
    // Set this pin's GPIO function (connect PIO to the pad)
    pio_gpio_init(pio, pin);
    // Set the pin direction to output at the PIO
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);
    // Set the state machine running
    pio_sm_set_enabled(pio, sm, true);
}

#endif
