// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------------------------------- //
// Abhadra_Interpreter_program_instructions //
// ---------------------------------------- //

#define Abhadra_Interpreter_program_instructions_wrap_target 18
#define Abhadra_Interpreter_program_instructions_wrap 19

static const uint16_t Abhadra_Interpreter_program_instructions_program_instructions[] = {
    0x0030, //  0: jmp    !x, 16                     
    0x0010, //  1: jmp    16                         
    0x0044, //  2: jmp    x--, 4                     
    0xa029, //  3: mov    x, !x                      
    0x60a5, //  4: out    pc, 5                      
    0x0087, //  5: jmp    y--, 7                     
    0xa04a, //  6: mov    y, !y                      
    0x60a5, //  7: out    pc, 5                      
    0x40f0, //  8: in     osr, 16                    
    0x60a5, //  9: out    pc, 5                      
    0xa026, // 10: mov    x, isr                     
    0x60a5, // 11: out    pc, 5                      
    0xa046, // 12: mov    y, isr                     
    0x60a5, // 13: out    pc, 5                      
    0x40c1, // 14: in     isr, 1                     
    0x60a5, // 15: out    pc, 5                      
    0x6001, // 16: out    pins, 1                    
    0x00f0, // 17: jmp    !osre, 16                  
            //     .wrap_target
    0x80a0, // 18: pull   block                      
    0x60a5, // 19: out    pc, 5                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program Abhadra_Interpreter_program_instructions_program = {
    .instructions = Abhadra_Interpreter_program_instructions_program_instructions,
    .length = 20,
    .origin = -1,
};

static inline pio_sm_config Abhadra_Interpreter_program_instructions_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + Abhadra_Interpreter_program_instructions_wrap_target, offset + Abhadra_Interpreter_program_instructions_wrap);
    return c;
}

static inline void hello_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = hello_program_get_default_config(offset);
    // Map the state machine's OUT pin group to one pin, namely the `pin`
    // parameter to this function.
    sm_config_set_out_pins(&c, pin, 1);
    // Set this pin's GPIO function (connect PIO to the pad)
    pio_gpio_init(pio, pin);
    // Set the pin direction to output at the PIO
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);
    // Set the state machine running
    pio_sm_set_enabled(pio, sm, true);
}

#endif
